baseURL = "https://www.murillodigital.com/"
languageCode = "en-us"
title = "Leonardo Murillo's murillodigital.com"
theme = "ananke"
disqusShortname = "murillodigital"
DefaultContentLanguage = "en"
googleAnalytics = "UA-68779688-2"
enableRobotsTXT = true

[params]
  favicon = ""
  site_logo = ""
  description = "Leonardo Murillo - Technology, business, the mind and our future"
  facebook = ""
  twitter = "https://twitter.com/murillodigital"
  instagram = ""
  youtube = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/leonardomurillo/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  recent_posts_number = 5
  custom_css = ["css/custom.css"]
  mainSections = ["tech_talk", "good_reads", "life_hacks"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true