baseURL = "https://www.murillodigital.com/"
languageCode = "en-us"
title = "Leonardo Murillo"
theme = "ananke"
disqusShortname = "murillodigital"
DefaultContentLanguage = "en"
googleAnalytics = "UA-68779688-2"
enableRobotsTXT = true

[params]
  favicon = ""
  site_logo = ""
  description = "Leonardo Murillo - Technology, business, the mind and our future"
  facebook = ""
  twitter = "https://twitter.com/murillodigital"
  instagram = ""
  youtube = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/leonardomurillo/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10